### ISSUE TITLE
Anyone achieved to reproduce the results ?

### ISSUE THREAD

**Issue by AlbinSou** [GeorgeTzannetos/ml-leaks-pytorch#2]
Running this code I obtained a maximum of 55% precision for attacker 1 on cifar10. Which is more or less what I get with my pytorch implementation. But in the paper they report 80% precision for this same dataset. Is there something we are doing wrong here ?

**Comment by GeorgeTzannetos** [comment]
Hi Albin, I also got the same as you. I assume some tricks are involved during training to match the performance reported on the paper, but I only spent a little time on that.
